# Generated by Django 5.0.6 on 2024-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_type", models.CharField(max_length=200)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("guest_name", models.CharField(max_length=200)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(max_length=200)),
                ("guest_address", models.CharField(max_length=200)),
                ("guest_city", models.CharField(max_length=200)),
                ("guest_state", models.CharField(max_length=200)),
                ("guest_zip", models.CharField(max_length=200)),
                ("guest_country", models.CharField(max_length=200)),
                ("guest_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
